### ISSUE TITLE
CSS file not found

### ISSUE THREAD

**Issue by hiwelo** [kwott/SimpleQuoteManager#28]
After my install, I've got this message when I check my CSS file : 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /kwott-app/assets/style/dist/main.css was not found on this server.</p>
</body></html>
```

And I cannot found the folder…

**Comment by Rudloff** [comment]
This file is generated by grunt.
Did you follow the new [README](https://github.com/kwott/SimpleQuoteManager/blob/master/README.md) and run grunt?
